spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/mpesa_payments
    username: ${DCPIT_POSTGRES_USER:admin}
    password: ${DCPIT_POSTGRES_PASSWORD:maarifa}

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    clean-disabled: false
    validate-on-migrate: true
    clean-on-validation-error: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:9090/realms/blast-wave

encryption:
  secret-key: "fKp8wX#mN9$vL2@jR5tQ7yH3cE6nA4bD"
  salt: "c8e6d42a1f953b7e"

mpesa:
  environment: SANDBOX

logging:
  level:
    com.fortuneconnectltd.com.notifications: DEBUG
    org.springframework.security: DEBUG
    org.keycloak: DEBUG

