server.port: 20000

spring:
  application:
    name: Daraja Integration Toolkit

  profiles:
    active: dev

  modulith:
    detection-strategy: explicitly-annotated
    republish-outstanding-events-on-restart: true
    events:
      completion-mode: update

  #Diallow JPA from managing the database schema
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migrations
    baseline-on-migrate: true

mpesa:
  urls:
    sandbox:
      auth-url: https://sandbox.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials
      register-url: https://sandbox.safaricom.co.ke/mpesa/c2b/v1/registerurl
      stk-push-url: https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest
    prod:
      auth-url: https://api.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials
      register-url: https://api.safaricom.co.ke/mpesa/c2b/v1/registerurl
      stk-push-url: https://api.safaricom.co.ke/mpesa/stkpush/v1/processrequest

logging:
  level:
    root: INFO
  file:
    name: logs/daraja-application.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
